"""added_tanecnici

Revision ID: 20250107_added_tanecnici
Revises: 20241211_v3
Create Date: 2025-01-07 13:55:44.878087+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250107_added_tanecnici'
down_revision = '20241211_v3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tanecnici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jmeno', sa.String(length=50), nullable=False),
    sa.Column('lat', sa.Integer(), nullable=False),
    sa.Column('stt', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tanecnici')
    # ### end Alembic commands ###
